#! /bin/bash

set -xe

export ARCH="${ARCH:-$(uname -p)}"

if [ "$ARCH" == "i386" ]; then
    export ARCH=i686
fi

# build CMake
./configure --prefix=/usr --no-system-libs --parallel=$(nproc)
make -j$(nproc)
make DESTDIR=appdir install
find appdir/

# set up AppDir
mkdir -p appdir/usr/share/applications/
echo -e "[Desktop Entry]\nVersion=1.0\nName=CMake\nExec=cmake %f\nIcon=CMakeSetup\nTerminal=true\nX-MultipleArgs=false\nType=Application\nCategories=Development;\nStartupNotify=true\nMimeType=application/x-cmakecache;" > appdir/CMake.desktop
mkdir -p appdir/usr/share/icons/hicolor/{32x32,64x64,128x128}
cp Source/QtDialog/CMakeSetup32.png appdir/usr/share/icons/hicolor/32x32/CMakeSetup.png
cp Source/QtDialog/CMakeSetup64.png appdir/usr/share/icons/hicolor/64x64/CMakeSetup.png
cp Source/QtDialog/CMakeSetup128.png appdir/usr/share/icons/hicolor/128x128/CMakeSetup.png
cp appdir/usr/share/icons/hicolor/128x128/CMakeSetup.png appdir/

# install linuxdeployqt so that it won't require FUSE to run
wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage"
chmod a+x appimagetool-"$ARCH".AppImage
./appimagetool-"$ARCH".AppImage --appimage-extract

# prepare AppImage build
unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file

# set up AppRun
wget -c -nv https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-"$ARCH" -O appdir/AppRun

# bundle libraries and build AppImage
./squashfs-root/AppRun appdir/ cmake-continuous-"$ARCH".AppImage
