#! /bin/bash

set -xe

cd $(dirname "$0")/..

mkdir -p out/

if [ "$1" != "" ]; then
    ARCHS="$@"
else
    ARCHS=(x86_64 i686)
fi

for ARCH in "${ARCHS[@]}"; do
    case "$ARCH" in
        x86_64)
            DOCKER_IMAGE=debian
            ;;
        i686)
            DOCKER_IMAGE=i386/debian
            ;;
        *)
            echo "Unknown architecture: $ARCH"
            exit 1
            ;;
    esac

    docker run -it -e ARCH -v $(readlink -f out):/out -v $(readlink -f .):/AppImageKit -w /AppImageKit "$DOCKER_IMAGE" \
        /bin/bash -c ". travis/bootstrap-container && travis/build-appimage"
done
