#! /bin/bash

set -xe

export ARCH="${ARCH:-$(uname -m)}"

if [ "$ARCH" == "i686" ]; then
    export ARCH=i386
fi

# generate first Makefile
./configure --prefix=/usr --parallel=$(nproc) --no-qt-gui --system-curl

# build first version of CMake so that build can be reconfigured
make -j$(nproc) cmake
make install

# reconfigure CMake to make it a more "static" build and re-build
cmake . -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_C_STANDARD:STRING=11 \
    -DCMAKE_CXX_STANDARD:STRING=14 \
    -DCMAKE_C_FLAGS:STRING='-D_POSIX_C_SOURCE=199506L -D_POSIX_SOURCE=1 -D_SVID_SOURCE=1 -D_BSD_SOURCE=1' \
    -DCMAKE_EXE_LINKER_FLAGS:STRING='-static-libstdc++ -static-libgcc'

# build and install
make all -j$(nproc)
make install DESTDIR=appdir

# set up AppDir
mkdir -p appdir/usr/share/applications/
echo -e "[Desktop Entry]\nVersion=1.0\nName=CMake\nExec=cmake %f\nIcon=CMakeSetup\nTerminal=true\nX-MultipleArgs=false\nType=Application\nCategories=Development;\nStartupNotify=true\nMimeType=application/x-cmakecache;" > appdir/cmake.desktop
mkdir -p appdir/usr/share/icons/hicolor/{32x32,64x64,128x128}
cp Source/QtDialog/CMakeSetup32.png appdir/usr/share/icons/hicolor/32x32/CMakeSetup.png
cp Source/QtDialog/CMakeSetup64.png appdir/usr/share/icons/hicolor/64x64/CMakeSetup.png
cp Source/QtDialog/CMakeSetup128.png appdir/usr/share/icons/hicolor/128x128/CMakeSetup.png
cp appdir/usr/share/icons/hicolor/128x128/CMakeSetup.png appdir/

# install linuxdeployqt so that it won't require FUSE to run
wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-$ARCH.AppImage"
chmod a+x appimagetool-"$ARCH".AppImage
./appimagetool-"$ARCH".AppImage --appimage-extract

# prepare AppImage build
unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
export VERSION=$(git rev-parse --short HEAD) # linuxdeployqt uses this for naming the file

# set up AppRun
echo -e '#! /bin/sh\nexec "$APPDIR"/usr/bin/cmake "$@"' > appdir/AppRun
chmod +x appdir/AppRun

# bundle libraries and build AppImage
mkdir -p out/
./squashfs-root/AppRun appdir/ out/cmake-continuous-"$ARCH".AppImage
